# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: debc5eb66554368ba778a0bc71417ff1fc6567154f75273cb2b5e9d878fe618b3a1930c2a578231b9eea765e02b2250b3bdf6de67440efd3c6d8ef00af8ad512

test:
  secret_key_base: 3b535b6a24e0ff9022a42cb5ffd8e2c246162ec40b487c1c3ec6ca74388285085a4ec7942f9f309e7c44aba61a6e4b9a831e709cce773dce17448e9838c61c53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
